version: 2
updates:
  # Enable version updates for Rust/Cargo
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "eonseed/maintainers"
    commit-message:
      prefix: "cargo"
      include: "scope"

  # Enable version updates for Python dependencies in docs
  - package-ecosystem: "pip"
    directory: "/docs/perspt_book"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "eonseed/maintainers"
    commit-message:
      prefix: "docs"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "eonseed/maintainers"
    commit-message:
      prefix: "ci"
