# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

import os
import sys

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = 'Perspt'
copyright = '2025, Ronak Rathore, Vikrant Rathore'
author = 'Ronak Rathore, Vikrant Rathore'
release = '0.6.2'
version = '0.6.2'

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.ifconfig',
    'sphinx.ext.githubpages',
    'sphinx.ext.graphviz',
    'matplotlib.sphinxext.plot_directive',
    'myst_parser',
    'sphinx_copybutton',
    'sphinx_design',
    'sphinx_tabs.tabs',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = []

# The suffix(es) of source filenames.
source_suffix = {
    '.rst': None,
    '.md': 'myst_parser',
}

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
language = 'en'

# -- Development configuration -----------------------------------------------

# Show todos in output for development builds
todo_include_todos = True

# Keep warnings as warnings (don't turn them into errors for development)
suppress_warnings = [
    'myst.title_to_header',  # Suppress MyST title warnings during development
]

# Enable parallel reading and writing for faster builds
numfigs = True
numfig_format = {
    'figure': 'Figure %s',
    'table': 'Table %s',
    'code-block': 'Listing %s',
    'section': 'Section %s',
}

# Better source file change detection for autobuild
html_use_smartypants = True
html_copy_source = True
html_show_sourcelink = True

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = 'furo'
html_title = f"{project} v{version}"
html_logo = None  # Add path to logo if available

# Theme options are theme-specific and customize the look and feel of a theme
html_theme_options = {
    "sidebar_hide_name": True,
    "light_css_variables": {
        "color-brand-primary": "#2563eb",
        "color-brand-content": "#2563eb",
        "color-admonition-background": "transparent",
    },
    "dark_css_variables": {
        "color-brand-primary": "#60a5fa",
        "color-brand-content": "#60a5fa",
        "color-admonition-background": "transparent",
    },
    "source_repository": "https://github.com/yourusername/perspt",
    "source_branch": "main",
    "source_directory": "docs/perspt_book/source/",
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']
html_css_files = ['custom.css']

# Get absolute path to font directory
font_dir = os.path.abspath(os.path.join(
    os.path.dirname(__file__), '_static/fonts'))
font_dir = font_dir.replace('\\', '/') # Convert to forward slashes for LaTeX

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
html_sidebars = {
    "**": [
        "sidebar/scroll-start.html",
        "sidebar/brand.html",
        "sidebar/search.html",
        "sidebar/navigation.html",
        "sidebar/ethical-ads.html",
        "sidebar/scroll-end.html",
    ]
}

# -- Options for LaTeX output ------------------------------------------------

latex_engine = 'lualatex'  # LuaHBLaTeX for excellent Unicode and emoji support
latex_elements = {
    'papersize': 'letterpaper',
    'pointsize': '10pt',
    'maketitle': r'''
\begin{titlepage}
    \thispagestyle{empty}
    \pagecolor{CoverBG}
    
    \centering
    \vspace*{0.4cm}
    
    {\fontsize{44}{52}\selectfont\bfseries P E R S P T} \\[0.4cm]
    \rule{\textwidth}{1.0pt} \\[0.4cm]
    {\fontsize{13}{16}\selectfont\scshape Your Terminal's Window to the AI World} \\[0.8cm]
    
    \begin{tikzpicture}[scale=1.0, every node/.style={transform shape}]
        \definecolor{CoverBG}{HTML}{EBE3CD}
        \definecolor{PrimaryColor}{HTML}{00D4AA}
        \definecolor{AccentColor}{HTML}{6366F1}
        \definecolor{SlateColor}{HTML}{475569}
        \definecolor{LightSlateColor}{HTML}{94A3B8}
        \definecolor{DarkSlateColor}{HTML}{0F172A}
        \definecolor{GliderColor}{HTML}{F59E0B}
        
        % Clip region to keep it clean and ensure no frame clipping
        \clip (-6.5, -4.5) rectangle (6.5, 4.5);
        
        % Double border frame
        \draw[black, double, double distance=2.5pt, thick] (-6, -4.25) rectangle (6, 4.25);
        
        % Quadrant alignment axes
        \draw[black, thin] (-6, 0) -- (6, 0);
        \draw[black, thin] (0, -4.25) -- (0, 4.25);
        
        % TOP-RIGHT: 3D Lyapunov Attractor (Cone & Spiral)
        \begin{scope}
            \draw[SlateColor!50, thin] (3, 0.4) ellipse (1.8 and 0.4);
            \draw[SlateColor!70, thick] (3, 3.8) -- (1.2, 0.4);
            \draw[SlateColor!70, thick] (3, 3.8) -- (4.8, 0.4);
            
            % Spiral path converging to apex
            \draw[PrimaryColor, very thick, ->, >=stealth, smooth, samples=150, domain=0:12.5]
                plot ({3 + (1 - \x/12.5) * 1.8 * cos(\x r)}, {0.4 + \x/12.5 * 3.4 + (1 - \x/12.5) * 0.4 * sin(\x r)});
            
            \node[right, color=SlateColor, font=\tiny\sffamily] at (3.8, 2.5) {3D State Space $\mathcal{X}$};
            \node[above, color=SlateColor, font=\tiny\sffamily] at (3, 3.8) {Attractor (Apex)};
        \end{scope}
        
        % BOTTOM-RIGHT: 2D Lyapunov Level Sets & Projected Trajectory
        \begin{scope}
            \coordinate (Sink) at (3, -2.125);
            
            % Concentric circles
            \foreach \k in {1, 2, 3, 4} {
                \draw[AccentColor!50, thin, dashed] (Sink) circle (\k * 0.45);
                \node[font=\tiny\sffamily, fill=CoverBG, text=AccentColor!80, inner sep=1pt] at (3, -2.125 + \k * 0.45) {$V_k = c_{\k}$};
            }
            
            % Barrier Certificate Boundary B(x) = 0
            \draw[red!75, thick] (Sink) circle (1.6);
            \node[font=\tiny\sffamily, fill=CoverBG, text=red!80, inner sep=1pt] at (3 + 1.13, -2.125 - 1.13) {$B(x) = 0$};
            
            % Projected 2D spiral
            \draw[PrimaryColor, very thick, ->, >=stealth, smooth, samples=150, domain=0:12.5]
                plot ({3 + 1.8 * exp(-0.25 * \x) * cos(\x r)}, {-2.125 + 1.8 * exp(-0.25 * \x) * sin(\x r)});
            
            \fill[PrimaryColor] (Sink) circle (2.5pt);
            \draw[PrimaryColor, thick] (Sink) circle (5pt);
            
            \node[below, color=SlateColor, font=\tiny\sffamily] at (3, -3.8) {Lyapunov Level Sets};
        \end{scope}
        
        % TOP-LEFT: 3D Swarm Topology (Sphere & Agent Network)
        \begin{scope}
            \coordinate (Center) at (-3, 2.125);
            \draw[SlateColor!50, thin] (Center) circle (1.6);
            \draw[SlateColor!40, thin, dashed] (Center) ellipse (1.6 and 0.4);
            \draw[SlateColor!40, thin, dashed] (Center) ellipse (0.4 and 1.6);
            
            \coordinate (N1) at (-3.8, 2.9);
            \coordinate (N2) at (-2.2, 2.8);
            \coordinate (N3) at (-2.5, 1.3);
            \coordinate (N4) at (-3.6, 1.2);
            \coordinate (N5) at (-3.0, 2.125);
            \coordinate (N6) at (-4.2, 2.0);
            \coordinate (N7) at (-1.8, 1.9);
            
            \draw[AccentColor!70, thin] (N1) -- (N2) -- (N7) -- (N3) -- (N4) -- (N6) -- (N1);
            \draw[AccentColor!70, thin] (N1) -- (N5);
            \draw[AccentColor!70, thin] (N2) -- (N5);
            \draw[AccentColor!70, thin] (N3) -- (N5);
            \draw[AccentColor!70, thin] (N4) -- (N5);
            \draw[AccentColor!70, thin] (N6) -- (N5);
            \draw[AccentColor!70, thin] (N7) -- (N5);
            
            \foreach \n in {N1, N2, N3, N4, N5, N6, N7} {
                \fill[PrimaryColor] (\n) circle (2.5pt);
                \draw[PrimaryColor!80, thin] (\n) circle (4pt);
            }
            
            \node[left, color=SlateColor, font=\tiny\sffamily] at (-4.7, 3.2) {ABM Swarm $\mathcal{S}$};
        \end{scope}
        
        % BOTTOM-LEFT: 2D Game of Life Glider Grid
        \begin{scope}
            % Grid
            \draw[SlateColor!40, thin] (-4.5, -3.6) grid[step=0.6] (-1.5, -0.6);
            
            % Hatched glider cells (Amber GliderColor)
            \foreach \X/\Y in {-3.9/-1.2, -3.3/-1.8, -3.3/-2.4, -3.9/-2.4, -4.5/-2.4} {
                \fill[GliderColor!20] (\X, \Y) rectangle (\X+0.6, \Y+0.6);
                \draw[GliderColor, thick] (\X, \Y) rectangle (\X+0.6, \Y+0.6);
                \foreach \o in {0.1, 0.2, 0.3, 0.4, 0.5} {
                    \draw[GliderColor!80, very thin] (\X + \o, \Y) -- (\X, \Y + \o);
                    \draw[GliderColor!80, very thin] (\X + 0.6, \Y + \o) -- (\X + \o, \Y + 0.6);
                }
            }
            
            \node[below, color=SlateColor, font=\tiny\sffamily] at (-3, -3.8) {Cellular Automata Projection};
        \end{scope}
        
        % Projection dashed lines
        \draw[LightSlateColor, thin, dashed] (4.8, 0.4) -- (4.8, -2.125);
        \draw[LightSlateColor, thin, dashed] (1.2, 0.4) -- (1.2, -2.125);
        \draw[LightSlateColor, thin, dashed] (-3, 0.525) -- (-3, -0.6);
        \draw[LightSlateColor, thin, dashed] (-4.6, 2.125) -- (-4.6, -2.1);
        \draw[LightSlateColor, thin, dashed] (-1.4, 2.125) -- (-1.4, -2.1);
        
        % Coupling sheaf dashed lines across columns
        \draw[AccentColor!70, dashed, thick] (-1.5, 2.125) to [out=20, in=160] (1.2, 2.125);
        \draw[PrimaryColor!70, dashed, thick] (-1.5, -2.125) to [out=-20, in=-160] (1.4, -2.125);
        \node[font=\tiny\itshape\sffamily, fill=CoverBG, text=AccentColor!80, inner sep=1pt] at (0, 2.4) {Sheaf Cohomology};
        \node[font=\tiny\itshape\sffamily, fill=CoverBG, text=PrimaryColor!80, inner sep=1pt] at (0, -2.4) {Energy Coupling};
        
    \end{tikzpicture}
    
    \vspace{0.6cm}
    
    \begin{center}
        \begin{minipage}{0.65\textwidth}
            \raggedright
            \fontsize{12}{18}\selectfont\itshape\color{black!90}
            The keyboard hums, the screen aglow,\\
            AI's wisdom, a steady flow.\\[0.4em]
            Will robots take over, it's quite the fright,\\
            Or just provide insights, day and night?\\[0.4em]
            We ponder and chat, with code as our guide,\\
            Is AI our helper or our human pride?
        \end{minipage}
    \end{center}
    
    \vspace{0.4cm}
    
    {\fontsize{13}{15}\selectfont\scshape\color{black} Ronak Rathore \quad \bullet \quad Vikrant Rathore} \\
    
    \vfill
    
    {\fontsize{11}{13}\selectfont\scshape\color{black!80} 2026}
\end{titlepage}
\pagecolor{white}
\cleardoublepage
''',
    'preamble': r'''
% XeLaTeX Unicode and font configuration
\usepackage{fontspec}
\usepackage{unicode-math}
\usepackage{tikz}
\usetikzlibrary{shapes,arrows,positioning,calc}

% Font selection with Unicode support
\setmainfont{Times New Roman}[
    Ligatures=TeX,
]
\setsansfont{Helvetica Neue}[
    Scale=0.9,
    Ligatures=TeX,
]
\setmonofont{Menlo}[
    Scale=0.85,
]

% Color definitions
\usepackage{xcolor}
\definecolor{TitleColor}{RGB}{37, 99, 235}
\definecolor{AccentColor}{RGB}{99, 102, 241}
\definecolor{PrimaryColor}{HTML}{00D4AA}
\definecolor{SlateColor}{HTML}{475569}
\definecolor{LightSlateColor}{HTML}{94A3B8}
\definecolor{DarkSlateColor}{HTML}{0F172A}
\definecolor{CoverBG}{HTML}{EBE3CD}

% Title formatting
\usepackage{titlesec}
\titleformat{\chapter}[display]
  {\normalfont\huge\bfseries\color{TitleColor}}
  {\chaptertitlename\ \thechapter}{20pt}{\Huge}
\titleformat{\section}
  {\normalfont\Large\bfseries\color{TitleColor}}
  {\thesection}{1em}{}
\titleformat{\subsection}
  {\normalfont\large\bfseries\color{AccentColor}}
  {\thesubsection}{1em}{}

% Better spacing and typography
\usepackage{microtype}
\usepackage{enumitem}
\setlist{nosep}

% Increase list nesting depth limits to handle deeply nested code structures
% Configure enumitem to allow deeper nesting
\setlistdepth{9}

% Configure description list formatting for deeper nesting
\setlist[description,1]{leftmargin=\parindent,labelindent=\parindent}
\setlist[description,2]{leftmargin=2\parindent,labelindent=2\parindent}
\setlist[description,3]{leftmargin=3\parindent,labelindent=3\parindent}
\setlist[description,4]{leftmargin=4\parindent,labelindent=4\parindent}
\setlist[description,5]{leftmargin=5\parindent,labelindent=5\parindent}
\setlist[description,6]{leftmargin=6\parindent,labelindent=6\parindent}
\setlist[description,7]{leftmargin=7\parindent,labelindent=7\parindent}
\setlist[description,8]{leftmargin=8\parindent,labelindent=8\parindent}
\setlist[description,9]{leftmargin=9\parindent,labelindent=9\parindent}

% Configure emoji fonts for Unicode emoji rendering
% Use system font with full path specification for XeLaTeX
\usepackage{newunicodechar}'''+f'''
\\newfontfamily\\emojifont{{NotoColorEmoji}}[
    Path={font_dir}/,
    Scale=1.0,
    Extension = .ttf,
    UprightFont=*
]'''+r'''
% Define all emojis used in documentation with primary font
\newunicodechar{🎉}{{\emojifont 🎉}}
\newunicodechar{🎨}{{\emojifont 🎨}}
\newunicodechar{🎯}{{\emojifont 🎯}}
\newunicodechar{🏗}{{\emojifont 🏗}}
\newunicodechar{🐌}{{\emojifont 🐌}}
\newunicodechar{👁}{{\emojifont 👁}}
\newunicodechar{📋}{{\emojifont 📋}}
\newunicodechar{📖}{{\emojifont 📖}}
\newunicodechar{📚}{{\emojifont 📚}}
\newunicodechar{📜}{{\emojifont 📜}}
\newunicodechar{📦}{{\emojifont 📦}}
\newunicodechar{🔀}{{\emojifont 🔀}}
\newunicodechar{🔄}{{\emojifont 🔄}}
\newunicodechar{🔒}{{\emojifont 🔒}}
\newunicodechar{🔗}{{\emojifont 🔗}}
\newunicodechar{🔧}{{\emojifont 🔧}}
\newunicodechar{🚀}{{\emojifont 🚀}}
\newunicodechar{🚫}{{\emojifont 🚫}}
\newunicodechar{🛠}{{\emojifont 🛠}}
\newunicodechar{🛡}{{\emojifont 🛡}}
\newunicodechar{🤖}{{\emojifont 🤖}}
\newunicodechar{🦀}{{\emojifont 🦀}}

% Additional common emojis that might be used
\newunicodechar{✨}{{\emojifont ✨}}
\newunicodechar{⚡}{{\emojifont ⚡}}
\newunicodechar{⚙}{{\emojifont ⚙}}
\newunicodechar{🔌}{{\emojifont 🔌}}
\newunicodechar{🔬}{{\emojifont 🔬}}
\newunicodechar{🧪}{{\emojifont 🧪}}
\newunicodechar{📝}{{\emojifont 📝}}
\newunicodechar{💰}{{\emojifont 💰}}
\newunicodechar{🖥}{{\emojifont 🖥}}
\newunicodechar{💾}{{\emojifont 💾}}
\newunicodechar{🤝}{{\emojifont 🤝}}
\newunicodechar{🧩}{{\emojifont 🧩}}
\newunicodechar{⚠}{{\emojifont ⚠}}
\newunicodechar{✅}{{\emojifont ✅}}
\newunicodechar{❗}{{\emojifont ❗}}
\newunicodechar{💡}{{\emojifont 💡}}
\newunicodechar{🎓}{{\emojifont 🎓}}
\newunicodechar{📎}{{\emojifont 📎}}
\newunicodechar{🧠}{{\emojifont 🧠}}
\newunicodechar{💻}{{\emojifont 💻}}
\newunicodechar{⌨}{{\emojifont ⌨}}
\newunicodechar{❌}{{\emojifont ❌}}
\newunicodechar{✗}{{\emojifont ✗}}
\newunicodechar{️}{{}}  % Variation selector - render as nothing

% Emoji command for manual usage
\newcommand{\emoji}[1]{{\emojifont #1}}
''',
    'fncychap': '\\usepackage[Bjornstrup]{fncychap}',
    'printindex': '\\footnotesize\\raggedright\\printindex',
}

latex_documents = [
    (master_doc, 'perspt.tex', 'Perspt Documentation',
     'Ronak Rathore, Vikrant Rathore', 'manual'),
]

# -- Options for manual page output ------------------------------------------

man_pages = [
    (master_doc, 'perspt', 'Perspt Documentation',
     [author], 1)
]

# -- Options for Texinfo output ----------------------------------------------

texinfo_documents = [
    (master_doc, 'Perspt', 'Perspt Documentation',
     author, 'Perspt', 'Your Terminal\'s Window to the AI World.',
     'Miscellaneous'),
]

# -- Extension configuration -------------------------------------------------

# -- Options for intersphinx extension ---------------------------------------

intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    # Rust docs don't provide stable inventory, so we'll disable it for now
    # 'rust': ('https://doc.rust-lang.org/stable/', None),
}

# -- Options for todo extension ----------------------------------------------

todo_include_todos = True

# Napoleon settings
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = False
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_preprocess_types = False
napoleon_type_aliases = None
napoleon_attr_annotations = True

# Graphviz configuration for diagram rendering
graphviz_output_format = 'png'  # PNG for HTML
graphviz_dot = 'dot'
graphviz_dot_args = ['-Gdpi=150']  # Higher DPI for better PDF quality

# Matplotlib plot directive configuration. The HTML builder consumes the PNG
# rendering while the LaTeX/PDF builder automatically selects the PDF rendering,
# so the same `.. plot::` block works for both outputs.
plot_include_source = False
plot_html_show_source_link = False
plot_html_show_formats = False
plot_formats = [('png', 150), 'pdf']
plot_rcparams = {
    'figure.figsize': (7.0, 4.0),
    'figure.dpi': 150,
    'savefig.bbox': 'tight',
    'font.size': 10,
    'axes.grid': True,
    'grid.alpha': 0.3,
}
plot_apply_rcparams = True

# MyST parser configuration
myst_enable_extensions = [
    "colon_fence",
    "deflist",
    "dollarmath",
    "fieldlist",
    "html_admonition",
    "html_image",
    "linkify",
    "replacements",
    "smartquotes",
    "strikethrough",
    "substitution",
    "tasklist",
]

# Sphinx-copybutton configuration
copybutton_prompt_text = r">>> |\.\.\. |\$ |In \[\d*\]: | {2,5}\.\.\.: | {5,8}: "
copybutton_prompt_is_regexp = True
