//! Agent Events
//!
//! Event types for communication between the SRBN Orchestrator and TUI.
//! Enables async, decoupled control flow for interactive agent sessions.

use serde::{Deserialize, Serialize};

/// Events emitted by the Orchestrator for TUI consumption
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum AgentEvent {
    /// Task status changed
    TaskStatusChanged { node_id: String, status: NodeStatus },

    /// Plan generated by Architect
    PlanGenerated(crate::types::TaskPlan),

    /// Lyapunov energy updated
    EnergyUpdated { node_id: String, energy: f32 },

    /// Log message for display
    Log(String),

    /// Node completed successfully
    NodeCompleted { node_id: String, goal: String },

    /// Approval required before proceeding
    ApprovalRequest {
        request_id: String,
        node_id: String,
        action_type: ActionType,
        description: String,
        diff: Option<String>,
    },

    /// Orchestration finished
    Complete { success: bool, message: String },

    /// Error occurred
    Error(String),

    // =========================================================================
    // PSP-5: Lifecycle Events
    // =========================================================================
    /// PSP-5: Plan ready after sheafification with detected plugins and execution mode
    PlanReady {
        nodes: usize,
        plugins: Vec<String>,
        execution_mode: String,
    },

    /// PSP-5: Node selected for execution
    NodeSelected {
        node_id: String,
        goal: String,
        node_class: String,
    },

    /// PSP-5: Deterministic fallback planner activated
    FallbackPlanner { reason: String },

    /// PSP-5: Verification completed for a node
    VerificationComplete {
        node_id: String,
        syntax_ok: bool,
        build_ok: bool,
        tests_ok: bool,
        diagnostics_count: usize,
        energy: f32,
    },

    /// PSP-5: Artifact bundle applied to workspace
    BundleApplied {
        node_id: String,
        files_created: Vec<String>,
        files_modified: Vec<String>,
    },
}

/// Node status for TUI display (mirrors NodeState but simplified)
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum NodeStatus {
    Pending,
    Running,
    Verifying,
    /// PSP-5: Node is retrying after a failed verification
    Retrying,
    Completed,
    Failed,
    Escalated,
}

/// Type of action requiring approval
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum ActionType {
    /// File creation or modification
    FileWrite { path: String },
    /// Shell command execution
    Command { command: String },
    /// Multiple files in a sub-graph
    SubGraph { node_count: usize },
    /// Project initialization (with editable name)
    ProjectInit {
        command: String,
        suggested_name: String,
    },
    /// PSP-5: Multi-file artifact bundle write
    BundleWrite {
        /// Node that produced the bundle
        node_id: String,
        /// Files being written or modified
        files: Vec<String>,
    },
}

/// Actions sent from TUI to Orchestrator
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum AgentAction {
    /// Approve a pending request
    Approve { request_id: String },
    /// Approve with an edited value (e.g., project name)
    ApproveWithEdit {
        request_id: String,
        edited_value: String,
    },
    /// Reject a pending request
    Reject {
        request_id: String,
        reason: Option<String>,
    },
    /// Pause orchestration
    Pause,
    /// Resume orchestration
    Resume,
    /// Abort the entire session
    Abort,
}

/// Channel types for agent communication
pub mod channel {
    use super::{AgentAction, AgentEvent};
    use tokio::sync::mpsc;

    /// Sender for AgentEvents (Orchestrator → TUI)
    pub type EventSender = mpsc::UnboundedSender<AgentEvent>;
    /// Receiver for AgentEvents (Orchestrator → TUI)
    pub type EventReceiver = mpsc::UnboundedReceiver<AgentEvent>;

    /// Sender for AgentActions (TUI → Orchestrator)
    pub type ActionSender = mpsc::UnboundedSender<AgentAction>;
    /// Receiver for AgentActions (TUI → Orchestrator)
    pub type ActionReceiver = mpsc::UnboundedReceiver<AgentAction>;

    /// Create event channel (Orchestrator → TUI)
    pub fn event_channel() -> (EventSender, EventReceiver) {
        mpsc::unbounded_channel()
    }

    /// Create action channel (TUI → Orchestrator)
    pub fn action_channel() -> (ActionSender, ActionReceiver) {
        mpsc::unbounded_channel()
    }
}
