# 🔧 Perspt Rustdoc Configuration
# This file configures cargo doc to use our custom assets and styling

[build]
# Enable unstable features for enhanced documentation
rustdocflags = [
    "--html-in-header", "docs/header.html",
    "--extend-css", "docs/custom.css",
    "--default-theme", "dark",
    # Note: Some advanced features removed due to rustdoc 1.87.0 compatibility
    # These features require nightly Rust or newer stable versions
]

# Additional configuration for documentation generation
[doc]
# Include all features in documentation
all-features = true
# Don't include dependencies in documentation
no-deps = true
# Open documentation after generation
open = true

# Custom documentation metadata
[package.metadata.docs.rs]
# Features to enable on docs.rs
features = ["default"]
# Default target for docs.rs
default-target = "x86_64-unknown-linux-gnu"
# Additional targets to document
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc", 
    "x86_64-apple-darwin",
    "aarch64-apple-darwin"
]
# Use docs.rs specific configuration
rustdoc-args = [
    "--cfg", "docsrs",
    "--html-in-header", "docs/header.html",
    "--extend-css", "docs/custom.css"
]
