//! Build-time compiler for Perspt prompt section files (PSP-10 system 23).
//!
//! Called from an owning crate's `build.rs`: it parses every
//! `prompts/<stage>/NN_name.md`, runs the codegen validation list, and
//! emits typed section structs into `OUT_DIR`. A malformed section fails
//! `cargo build` with an error naming the offending file — never a
//! session. The same validation functions serve the runtime bundle scanner
//! and `perspt prompts lint`, so external replacement bodies obey exactly
//! the rules the build does.

use std::fmt;
use std::path::Path;

use perspt_sdk::prompt::{
    PromptMessageRole, PromptSectionId, PromptSectionVersion, SectionSchema, SectionTemplate,
    VarSpec,
};

mod emit;
mod frontmatter;
mod types;
mod validate;

pub use frontmatter::{parse_section_file, FrontMatter, ParsedVar};
pub use types::VarType;
pub use validate::validate_section_body;

/// A build failure, naming the offending file (and line when known).
#[derive(Debug, Clone, PartialEq)]
pub struct PromptBuildError {
    pub file: String,
    pub line: Option<usize>,
    pub message: String,
}

impl fmt::Display for PromptBuildError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.line {
            Some(line) => write!(formatter, "{}:{line}: {}", self.file, self.message),
            None => write!(formatter, "{}: {}", self.file, self.message),
        }
    }
}

impl std::error::Error for PromptBuildError {}

/// One stage the owning crate declares (dir name plus the deterministic
/// separator its composed text joins with — a compilation input that
/// enters the program digest).
#[derive(Debug, Clone)]
pub struct StageDecl {
    pub dir_name: String,
    pub separator: String,
}

impl StageDecl {
    pub fn new(dir_name: impl Into<String>, separator: impl Into<String>) -> Self {
        Self {
            dir_name: dir_name.into(),
            separator: separator.into(),
        }
    }
}

/// One compiled section (base or override), for emission and manifest
/// validation.
#[derive(Debug, Clone)]
pub struct CompiledSection {
    pub stage: String,
    pub file_name: String,
    pub section_name: String,
    pub role_name: String,
    pub schema: SectionSchema,
    pub vars: Vec<ParsedVar>,
    pub body: String,
    pub content_hash: String,
    /// `Some(route_label)` for an override file `NN_name.<label>.md`.
    pub override_label: Option<String>,
}

/// The compiler's output: the generated Rust source and the compiled
/// section inventory.
#[derive(Debug, Clone)]
pub struct Generated {
    pub rust_source: String,
    pub sections: Vec<CompiledSection>,
}

/// Compile every declared stage under `root`. Fails closed on any invalid
/// file, a missing stage directory, or a stage with no base sections.
pub fn compile_prompt_dir(
    root: &Path,
    stages: &[StageDecl],
) -> Result<Generated, PromptBuildError> {
    let mut sections: Vec<CompiledSection> = Vec::new();
    let mut source = String::from("// @generated by perspt-prompt-macros — do not edit.\n\n");
    for stage in stages {
        let stage_sections = compile_stage(root, stage, &mut sections)?;
        source.push_str(&stage_sections);
        source.push('\n');
    }
    Ok(Generated {
        rust_source: source,
        sections,
    })
}

fn compile_stage(
    root: &Path,
    stage: &StageDecl,
    all: &mut Vec<CompiledSection>,
) -> Result<String, PromptBuildError> {
    let dir = root.join(&stage.dir_name);
    let dir_error = |message: String| PromptBuildError {
        file: dir.display().to_string(),
        line: None,
        message,
    };
    let mut names: Vec<String> = std::fs::read_dir(&dir)
        .map_err(|error| dir_error(format!("declared stage directory unreadable: {error}")))?
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.file_name().to_string_lossy().to_string())
        .filter(|name| name.ends_with(".md"))
        .collect();
    names.sort();
    let start = all.len();
    for name in &names {
        let section = compile_file(&dir, &stage.dir_name, name)?;
        all.push(section);
    }
    let stage_sections = &all[start..];
    let bases: Vec<&CompiledSection> = stage_sections
        .iter()
        .filter(|section| section.override_label.is_none())
        .collect();
    if bases.is_empty() {
        return Err(dir_error(
            "declared stage has no base sections; the build fails closed".into(),
        ));
    }
    for section in stage_sections
        .iter()
        .filter(|section| section.override_label.is_some())
    {
        let base = bases
            .iter()
            .find(|base| base.section_name == section.section_name)
            .ok_or_else(|| PromptBuildError {
                file: section.file_name.clone(),
                line: None,
                message: "override file has no base section beside it".into(),
            })?;
        check_override_schema(base, section)?;
    }
    let overrides: Vec<&CompiledSection> = stage_sections
        .iter()
        .filter(|section| section.override_label.is_some())
        .collect();
    Ok(emit::emit_stage(
        &stage.dir_name,
        &stage.separator,
        &bases,
        &overrides,
    ))
}

fn compile_file(
    dir: &Path,
    stage_name: &str,
    file_name: &str,
) -> Result<CompiledSection, PromptBuildError> {
    let path = dir.join(file_name);
    let display = path.display().to_string();
    let file_error = |message: String| PromptBuildError {
        file: display.clone(),
        line: None,
        message,
    };
    let (section_name, override_label) = parse_file_name(file_name).map_err(&file_error)?;
    let raw = std::fs::read_to_string(&path)
        .map_err(|error| file_error(format!("unreadable: {error}")))?;
    if !raw.ends_with('\n') || raw.ends_with("\n\n") {
        return Err(file_error(
            "section files must end with exactly one newline (byte-identity discipline)".into(),
        ));
    }
    let (matter, body) = parse_section_file(&display, &raw)?;
    let expected_id = format!("{stage_name}/{section_name}");
    if matter.id != expected_id {
        return Err(file_error(format!(
            "front-matter id {:?} must equal {expected_id:?} (from the file path)",
            matter.id
        )));
    }
    let body = body.strip_suffix('\n').unwrap_or(&body).to_string();
    let schema = build_schema(&matter);
    for var in &matter.vars {
        if !is_rust_ident(&var.name) {
            return Err(file_error(format!(
                "var {:?} is not a valid field identifier",
                var.name
            )));
        }
    }
    validate_section_body(&schema, &body).map_err(|error| PromptBuildError {
        file: display.clone(),
        line: error.line,
        message: error.message,
    })?;
    Ok(CompiledSection {
        stage: stage_name.to_string(),
        file_name: display,
        section_name,
        role_name: matter.role,
        content_hash: SectionTemplate::hash_body(&body),
        schema,
        vars: matter.vars,
        body,
        override_label,
    })
}

fn build_schema(matter: &FrontMatter) -> SectionSchema {
    SectionSchema {
        id: PromptSectionId(matter.id.clone()),
        version: PromptSectionVersion(matter.version),
        role: match matter.role.as_str() {
            "user" => PromptMessageRole::User,
            _ => PromptMessageRole::System,
        },
        required: matter.required,
        priority: matter.priority,
        max_bytes: matter.max_bytes,
        vars: matter
            .vars
            .iter()
            .map(|var| VarSpec {
                name: var.name.clone(),
                declared_type: var.declared_type.clone(),
                style: var.style,
            })
            .collect(),
    }
}

/// `10_role.md` → (`role`, None); `20_x.family_a.md` → (`x`, Some("family_a")).
fn parse_file_name(file_name: &str) -> Result<(String, Option<String>), String> {
    let stem = file_name
        .strip_suffix(".md")
        .ok_or_else(|| "not a .md file".to_string())?;
    let parts: Vec<&str> = stem.split('.').collect();
    let (base, label) = match parts.as_slice() {
        [base] => (*base, None),
        [base, label] => (*base, Some(label.to_string())),
        _ => return Err(format!("file name {file_name:?} has too many dots")),
    };
    let name = base
        .split_once('_')
        .filter(|(prefix, _)| prefix.chars().all(|c| c.is_ascii_digit()))
        .map(|(_, rest)| rest)
        .ok_or_else(|| format!("file name {file_name:?} must be `NN_name.md` (ordering prefix)"))?;
    if !is_rust_ident(name) {
        return Err(format!("section name {name:?} is not a valid identifier"));
    }
    Ok((name.to_string(), label))
}

fn is_rust_ident(name: &str) -> bool {
    let mut chars = name.chars();
    matches!(chars.next(), Some(first) if first.is_ascii_alphabetic() || first == '_')
        && chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

/// An override must share its base's variable schema, role, and budget
/// discipline exactly; only the prose differs (system 25).
fn check_override_schema(
    base: &CompiledSection,
    section: &CompiledSection,
) -> Result<(), PromptBuildError> {
    let mismatch = |what: &str| PromptBuildError {
        file: section.file_name.clone(),
        line: None,
        message: format!("override {what} differs from its base section"),
    };
    if section.schema.vars != base.schema.vars {
        return Err(mismatch("variable schema"));
    }
    if section.schema.role != base.schema.role {
        return Err(mismatch("role"));
    }
    if section.schema.required != base.schema.required
        || section.schema.priority != base.schema.priority
    {
        return Err(mismatch("required/priority"));
    }
    Ok(())
}

/// Validate a committed `manifest.toml` against the compiled sections: the
/// build never edits the tree, it only refuses to drift from it.
pub fn validate_manifest(
    manifest_path: &Path,
    sections: &[CompiledSection],
) -> Result<(), PromptBuildError> {
    let display = manifest_path.display().to_string();
    let err = |message: String| PromptBuildError {
        file: display.clone(),
        line: None,
        message: format!("{message}; regenerate with `perspt prompts manifest`"),
    };
    let raw = std::fs::read_to_string(manifest_path)
        .map_err(|error| err(format!("unreadable manifest: {error}")))?;
    let value: toml::Table = raw
        .parse()
        .map_err(|error| err(format!("unparseable manifest: {error}")))?;
    let entries = value
        .get("section")
        .and_then(|value| value.as_array())
        .ok_or_else(|| err("manifest has no [[section]] entries".into()))?;
    if entries.len() != sections.len() {
        return Err(err(format!(
            "manifest lists {} sections but {} are compiled",
            entries.len(),
            sections.len()
        )));
    }
    for section in sections {
        let key = match &section.override_label {
            None => section.schema.id.0.clone(),
            Some(label) => format!("{}.{label}", section.schema.id.0),
        };
        let entry = entries
            .iter()
            .find(|entry| {
                entry.get("id").and_then(|v| v.as_str()) == Some(section.schema.id.0.as_str())
                    && entry.get("override").and_then(|v| v.as_str())
                        == section.override_label.as_deref()
            })
            .ok_or_else(|| err(format!("manifest is missing {key}")))?;
        let hash = entry.get("content_hash").and_then(|v| v.as_str());
        if hash != Some(section.content_hash.as_str()) {
            return Err(err(format!("{key}: manifest content_hash is stale")));
        }
        let version = entry.get("version").and_then(|v| v.as_integer());
        if version != Some(i64::from(section.schema.version.0)) {
            return Err(err(format!("{key}: manifest version is stale")));
        }
    }
    Ok(())
}
