//! The ratchet.
//!
//! Perspt adopted these rules with eight files already over the limit, the
//! worst of them the 5,889-line orchestrator that PSP-9 rewrites anyway.
//! Failing the build on day one would have meant either a monstrous
//! behaviour-neutral refactor before any feature work, or — far more likely —
//! switching the check off.
//!
//! So the baseline records what is owed today. [`evaluate`] fails only when a
//! count *grows* or a new file appears, and `baseline --shrink` writes smaller
//! numbers only. Legacy debt is visible and cannot deepen; every file that
//! gets decomposed drops out permanently. The target state is an empty file.

use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

use crate::rules::{RuleId, Violation};

/// Where the ratchet lives, relative to the repository root.
pub const BASELINE_PATH: &str = ".nasa-baseline.toml";

/// One `(file, rule)` pair and the number of violations tolerated in it.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Allowance {
    pub file: String,
    pub rule: RuleId,
    pub count: usize,
}

/// The accepted debt, as loaded from [`BASELINE_PATH`].
#[derive(Debug, Default, Clone, Serialize, Deserialize)]
pub struct Baseline {
    #[serde(default, rename = "allow")]
    pub allowances: Vec<Allowance>,
}

/// A `(file, rule)` pair whose count exceeds what the baseline permits.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Regression {
    pub file: String,
    pub rule: RuleId,
    pub allowed: usize,
    pub found: usize,
}

/// A `(file, rule)` pair that improved and can be ratcheted down.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Improvement {
    pub file: String,
    pub rule: RuleId,
    pub allowed: usize,
    pub found: usize,
}

impl Baseline {
    /// Load the baseline, treating a missing file as no accepted debt.
    pub fn load(root: &Path) -> Result<Self> {
        let path = root.join(BASELINE_PATH);
        if !path.exists() {
            return Ok(Self::default());
        }
        let text =
            fs::read_to_string(&path).with_context(|| format!("reading {}", path.display()))?;
        toml::from_str(&text).with_context(|| format!("parsing {}", path.display()))
    }

    /// Build a baseline that exactly covers `violations`.
    pub fn from_violations(violations: &[Violation]) -> Self {
        let mut allowances: Vec<Allowance> = tally(violations)
            .into_iter()
            .map(|((file, rule), count)| Allowance { file, rule, count })
            .collect();
        allowances.sort_by(|a, b| (&a.file, a.rule).cmp(&(&b.file, b.rule)));
        Self { allowances }
    }

    /// How many violations of `rule` are tolerated in `file`.
    pub fn allowed(&self, file: &str, rule: RuleId) -> usize {
        self.allowances
            .iter()
            .find(|a| a.file == file && a.rule == rule)
            .map_or(0, |a| a.count)
    }

    /// Whether any debt is recorded at all.
    pub fn is_clean(&self) -> bool {
        self.allowances.is_empty()
    }

    /// Write the baseline with a header explaining the ratchet.
    pub fn save(&self, root: &Path) -> Result<()> {
        let path = root.join(BASELINE_PATH);
        let body = toml::to_string_pretty(self).context("serializing the baseline")?;
        let text = format!(
            "# NASA coding-rule baseline for Perspt.\n\
             #\n\
             # Generated by `cargo xtask baseline`. Each entry is debt accepted at the\n\
             # time the rules were adopted. Counts may only shrink: `cargo xtask check`\n\
             # fails if one grows or a new file appears. Delete entries by decomposing\n\
             # the file, never by raising the number.\n\
             #\n\
             # The target state is an empty file.\n\n{body}"
        );
        fs::write(&path, text).with_context(|| format!("writing {}", path.display()))
    }
}

/// Compare the current violations against accepted debt.
///
/// Returns the pairs that got worse and the pairs that got better, so `check`
/// can fail on the former and `baseline --shrink` can act on the latter.
pub fn evaluate(
    violations: &[Violation],
    baseline: &Baseline,
) -> (Vec<Regression>, Vec<Improvement>) {
    let counts = tally(violations);
    let mut regressions = Vec::new();
    for ((file, rule), found) in &counts {
        let allowed = baseline.allowed(file, *rule);
        if *found > allowed {
            regressions.push(Regression {
                file: file.clone(),
                rule: *rule,
                allowed,
                found: *found,
            });
        }
    }

    let mut improvements = Vec::new();
    for allowance in &baseline.allowances {
        let found = counts
            .get(&(allowance.file.clone(), allowance.rule))
            .copied()
            .unwrap_or(0);
        if found < allowance.count {
            improvements.push(Improvement {
                file: allowance.file.clone(),
                rule: allowance.rule,
                allowed: allowance.count,
                found,
            });
        }
    }

    regressions.sort_by(|a, b| (&a.file, a.rule).cmp(&(&b.file, b.rule)));
    improvements.sort_by(|a, b| (&a.file, a.rule).cmp(&(&b.file, b.rule)));
    (regressions, improvements)
}

/// Count violations per `(file, rule)`.
fn tally(violations: &[Violation]) -> BTreeMap<(String, RuleId), usize> {
    let mut counts = BTreeMap::new();
    for violation in violations {
        let key = (violation.file.display().to_string(), violation.rule);
        *counts.entry(key).or_insert(0) += 1;
    }
    counts
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn violation(file: &str, rule: RuleId) -> Violation {
        Violation {
            rule,
            file: PathBuf::from(file),
            line: 1,
            item: None,
            measured: 2000,
            limit: rule.limit(),
        }
    }

    #[test]
    fn a_baseline_covers_exactly_what_it_was_built_from() {
        let found = [
            violation("a.rs", RuleId::FileLength),
            violation("a.rs", RuleId::LineWidth),
        ];
        let baseline = Baseline::from_violations(&found);
        let (regressions, improvements) = evaluate(&found, &baseline);
        assert!(regressions.is_empty());
        assert!(improvements.is_empty());
    }

    #[test]
    fn a_growing_count_is_a_regression() {
        let baseline = Baseline::from_violations(&[violation("a.rs", RuleId::LineWidth)]);
        let worse = [
            violation("a.rs", RuleId::LineWidth),
            violation("a.rs", RuleId::LineWidth),
        ];
        let (regressions, _) = evaluate(&worse, &baseline);
        assert_eq!(regressions.len(), 1);
        assert_eq!(regressions[0].allowed, 1);
        assert_eq!(regressions[0].found, 2);
    }

    #[test]
    fn an_untracked_file_is_a_regression_even_at_one_violation() {
        let baseline = Baseline::default();
        let (regressions, _) = evaluate(&[violation("new.rs", RuleId::FileLength)], &baseline);
        assert_eq!(regressions.len(), 1);
        assert_eq!(regressions[0].allowed, 0);
    }

    #[test]
    fn a_shrinking_count_is_an_improvement_and_never_fails_the_check() {
        let baseline = Baseline::from_violations(&[
            violation("a.rs", RuleId::LineWidth),
            violation("a.rs", RuleId::LineWidth),
        ]);
        let (regressions, improvements) =
            evaluate(&[violation("a.rs", RuleId::LineWidth)], &baseline);
        assert!(regressions.is_empty());
        assert_eq!(improvements.len(), 1);
        assert_eq!(improvements[0].allowed, 2);
        assert_eq!(improvements[0].found, 1);
    }

    #[test]
    fn a_fully_fixed_file_is_reported_as_removable() {
        let baseline = Baseline::from_violations(&[violation("a.rs", RuleId::FileLength)]);
        let (_, improvements) = evaluate(&[], &baseline);
        assert_eq!(improvements.len(), 1);
        assert_eq!(improvements[0].found, 0);
    }

    #[test]
    fn rules_serialize_under_their_public_codes() {
        let baseline = Baseline::from_violations(&[violation("a.rs", RuleId::FunctionLength)]);
        let text = toml::to_string_pretty(&baseline).expect("serializes");
        assert!(text.contains("NASA-2"), "{text}");
    }
}
