name: Deploy Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'src/**'
      - 'Cargo.toml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-docs-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-docs-

    - name: Build Rust documentation
      run: cargo doc --no-deps --all-features

    - name: Build Sphinx documentation
      run: |
        cd docs/perspt_book
        uv run make html

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Prepare documentation for Pages
      run: |
        mkdir -p _site
        
        # Create index page that links to both documentations
        cat > _site/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Perspt Documentation</title>
            <style>
                body {
                    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
                    max-width: 800px;
                    margin: 0 auto;
                    padding: 2rem;
                    background: #f8f9fa;
                }
                .container {
                    background: white;
                    padding: 2rem;
                    border-radius: 8px;
                    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
                }
                h1 {
                    color: #2c3e50;
                    border-bottom: 2px solid #3498db;
                    padding-bottom: 0.5rem;
                }
                .doc-links {
                    display: grid;
                    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
                    gap: 1.5rem;
                    margin-top: 2rem;
                }
                .doc-card {
                    border: 1px solid #ddd;
                    border-radius: 6px;
                    padding: 1.5rem;
                    text-decoration: none;
                    color: inherit;
                    transition: transform 0.2s, box-shadow 0.2s;
                }
                .doc-card:hover {
                    transform: translateY(-2px);
                    box-shadow: 0 4px 15px rgba(0,0,0,0.1);
                }
                .doc-card h3 {
                    margin: 0 0 0.5rem 0;
                    color: #3498db;
                }
                .doc-card p {
                    margin: 0;
                    color: #666;
                }
            </style>
        </head>
        <body>
            <div class="container">
                <h1>Perspt Documentation</h1>
                <p>Welcome to the Perspt documentation. Choose from the available documentation types below:</p>
                
                <div class="doc-links">
                    <a href="./sphinx/" class="doc-card">
                        <h3>📚 Perspt Book</h3>
                        <p>Complete window into perspt for users, developers, rustaceans and enthusiasts.</p>
                    </a>
                    
                    <a href="./rust-docs/" class="doc-card">
                        <h3>🔧 API Documentation</h3>
                        <p>Rust API documentation generated from source code. Detailed information about modules, functions, and data structures.</p>
                    </a>
                </div>
            </div>
        </body>
        </html>
        EOF
        
        # Copy Sphinx documentation
        cp -r docs/perspt_book/build/html _site/sphinx
        
        # Copy Rust documentation
        cp -r target/doc _site/rust-docs

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3

  deploy:
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-docs
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
